apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
  - image: lmsb2-gke-multiplication
    context: multiplication
    buildpacks:
      builder: gcr.io/buildpacks/builder
      env:
      - GOOGLE_RUNTIME_VERSION=15
  - image: lmsb2-gke-gamification
    context: gamification
    buildpacks:
      builder: gcr.io/buildpacks/builder
      env:
      - GOOGLE_RUNTIME_VERSION=15
  - image: lmsb2-gke-frontend
    context: challenges-frontend
    buildpacks:
      builder: gcr.io/buildpacks/builder
      env:
      - NODE_ENV=development
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
