apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: java-guestbook-backend
    jib:
      project: backend
  - image: java-guestbook-frontend
    jib:
      project: frontend
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: java-guestbook-backend
      context: backend
    - image: java-guestbook-frontend
      context: frontend
