apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmsb2-gke-gamification
  labels:
    app: lmsb2-gke
    tier: gamification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmsb2-gke
      tier: gamification
  template:
    metadata:
      labels:
        app: lmsb2-gke
        tier: gamification
    spec:
      containers:
      - name: gamification
        image: lmsb2-gke-gamification
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
