apiVersion: v1
kind: Service
metadata:
  name: lmsb2-gke-backend
  labels:
    app: lmsb2-gke
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: lmsb2-gke
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
